# What is Unix?

Unix is an operating system and a set of tools. The tool we will be using the
most in this book is a shell, which is a computer program that provides a
command line interface. You have probably seen a command line interface in the
movies: an elite computer hacker sits in front of a black screen with green 
glowing text, furiously typing in commands and shouting something like 
"Spike them!" Using the command line interface lets you enter lines of code into
a shell (also called a console) and that code instructs your computer to
perform a specific task. Throughout this book I may use the terms command line,
shell, and console interchangeably. You will learn about using the command line
in the Command Line Basics chapter.

The shell is a very direct and powerful way to manipulate a computer. You
can produce wonderful creations that help thousands of people, or you can wreak
havoc on yourself and on others. Like
[Benjamin Parker](https://en.wikipedia.org/wiki/Uncle_Ben) once 
said: "With great power comes great responsibility."

There are several popular shell programs but in this book we'll be using a shell 
called Bash because it is the default shell program on Mac and Ubuntu.
