# Nephology

> I saw a city in the clouds. - Dagobahnian proverb

Nephology is the study of clouds. Few modern technology concepts (other than 
maybe data science and artificial intelligence) have been hyped as loudly as "the
cloud." The cloud is simply a computer which you can access over the interent.
In this chapter we'll meet some cloud computers and we'll learn the basics of 
interacting with them.

To get the most out of the this chapter you're going to need your credit or
debit card, or a [PayPal](https://www.paypal.com) account. We're going to be
using [DigitalOcean](https://m.do.co/c/530d6cfa2b37), a company from which you
can rent cloud computers. Throughout this chapter I might refer to cloud
computers as **servers** (computers connected to the internet) or as
**droplets**, which a marketing term DigitalOcean uses to refer to their
servers (a droplet is *not* a technical term). Renting from DigitalOcean won't
cost you any money since I'm giving you a coupon for two free months of service!

**Warning:** *At the end of this chapter we will discuss how to shut down any
servers you've started on DigitalOcean. If you don't shut down your server
after two months then your account will be charged real money for using
DigitalOcean.*




- click link to sign up
- enter email and password
- check your email
- follow link
- enter CC or PayPal info



First

ssh, scp, curl, cron, ps